apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlpage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: htmlpage
  template:
    metadata:
      labels:
        app: htmlpage
    spec:
      containers:
      - name: htmlpage-container
        image: msshankar/htmlpage:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: htmlpage-service
spec:
  type: NodePort
  selector:
    app: htmlpage
  ports:
    - protocol: TCP
      port: 80         # service port
      targetPort: 3000 # container port
      nodePort: 30080  # node port (must be between 30000-32767)
