- name: Deploy app to EKS cluster
  hosts: localhost
  tasks:
    - name: Apply Kubernetes manifests
      shell: |
        kubectl apply -f k8s/deployment.yaml --kubeconfig=/home/jenkins/.kube/config
