- name: Deploy app to EKS
  hosts: localhost
  tasks:
    - name: Update image in deployment manifest
      replace:
        path: k8s/deployment.yaml
        regexp: 'image: msshankar/htmlpage:.*'
        replace: "image: msshankar/htmlpage:{{ lookup('env','BUILD_NUMBER') }}"

    - name: Apply deployment manifest
      shell: kubectl apply -f k8s/deployment.yaml --kubeconfig=/home/jenkins/.kube/config
